### ISSUE TITLE
Add node_modules to .gitignore

### ISSUE THREAD

**Issue by Musab-Nazir** [Soban-Farhan/Incubate#2]
node_modules should never be added to a repo because they can be fetched by node via the package.json

**Comment by Soban-Farhan** [comment]
That's true. I have been looking at file to remove from the git repo.  Hopefully next commit node_module is removed.

**Comment by Soban-Farhan** [comment]
I have removed node_modules from both root dir and client dir (frontend/React). Thanks again for pointing it out.
