### ISSUE TITLE
Merge server and client dependencies into one package.json

### ISSUE THREAD

**Issue by Musab-Nazir** [Soban-Farhan/Incubate#3]
I've thought more about this and generally its better to have a unified dependency list. If you look at the project scaffolding that occurs with dotnet react projects in visual studio, they use a single package.json and I believe thats the way it should be. Simplifies the workflow and provides a single source of truth for the dependencies

**Comment by Soban-Farhan** [comment]
Yes, that is true and I entirely agree. The reason why I didn't combine it earlier is that I was setting up two different servers. Also, during deployment, it reads the root package.json. In the future, I would have had to combine them either way.
